# Site wide configuration

title: Allixender.GitHub.io
description: Me doing some more stuff
logo: profile1-120.jpg # 120x120 px default image used for Twitter summary card
teaser: main-teaser-450.png # 400x250 px default teaser image used in image archive grid
locale: en_NZ
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Alex K
  email: allixender@googlemail.com
  twitter: allixender
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: profile1-120.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "README.SkinnyBones.md", "LICENSE", "LICENSE.SkinnyBones", "node_modules", "Gruntfile.js", "package.json"]
